# Exercise: Config and Deployment
configure_infrastructure: 
  docker:
    - image: 
  steps:
    - checkout
    - add_ssh_keys:
            # You can get this ID in the section where you registered the SSH Key
            fingerprints: ["2c:5a:d3:84:c2:5e:cb:d0:95:eb:dd:81:90:88:a1:7c"] 
    - run:
        name: Install Ansible
        command: |
          # Install Ansible
    - run:
        name: Run Playbook and Configure server
        command: |
workflows:
  my-workflow:
    jobs:
      - configure_infrastructure
